### ISSUE TITLE
pip install ?

### ISSUE THREAD

**Issue by cod65** [TauraBots/PyDynamixel#1]
I dont really know what I'm doing, but maybe this error is helpful to you (and me).
regards.

Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\SPACE1970>pip install pydynamixel
Collecting pydynamixel
  Using cached pydynamixel-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\space1~1\appdata\local\temp\pip-build-er0dn1\pydynamixel\setup.py", line 13, in <module>
        long_description = get_long_description(),
      File "c:\users\space1~1\appdata\local\temp\pip-build-er0dn1\pydynamixel\setup.py", line 4, in get_long_description
        f = open('README.rst')
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\space1~1\appdata\local\temp\pip-build-er0dn1\pydynamixel\

C:\Users\SPACE1970>

**Comment by juliopcrj** [comment]
Not ours.
